name: Build Rust

on:
  push:
    paths:
      - 'beecrowd/**/*.rs'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of modified files
      id: files
      run: echo "::set-output name=files::$(jq -r '.commits[] | .added + .modified' $GITHUB_EVENT_PATH | tr '\n' ',')"

    - name: Build modified Rust files
      run: |
        IFS=',' read -ra file_array <<< "${{ steps.files.outputs.files }}"
        for file in "${file_array[@]}"; do
          if [[ $file == *".rs"* ]]; then
            rustc $file
          fi
        done

    - name: Display compiled files
      run: |
        find beecrowd -type f -name "target" -prune -o -name "*.rs" -exec echo "Compiled: {}" \;
